### ISSUE TITLE
Install requirement - hdf5 headers

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#1]
`python setup.py install` fails with:

> fatal error: hdf5.h: No such file or directory
> #include "hdf5.h"

Can fix with `apt-get install libhdf5-dev`, but seems like it should be pulled in during the install of h5py.

**Comment by dereneaton** [comment]
That's interesting. I'm pretty sure it's pulled in automatically when you use conda, and maybe also with pip. We can probably ignore this problem for now since I'm not even sure that we're going to use h5py yet. At least I haven't implemented anything with it yet. 

Let's consider the 'requirements' in setup.py to be very malleable at this point.

**Comment by dereneaton** [comment]
Is it possible to write libhdf5-dev into the conda install recipe? How does this work on a mac?

**Comment by isaacovercast** [comment]
Hm. I double-checked this. Ran the conda build on clean mac and linux installs and it works fine (though I had to fix the meta.yaml a little). I documented the exact conda package build steps on the [Install and config](https://github.com/dereneaton/ipyrad/wiki/install-and-config) wiki page.
