### ISSUE TITLE
reordered keys after json load

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#116]
Probably need to use Ordereddicts somewhere. Not a priority cuz I don't think it will cause any problems, but it makes for prettier printing of results and API info if we fix it.

**Comment by dereneaton** [comment]
noticed it in data.dirs and data.statsfiles.s3 so far.

**Comment by isaacovercast** [comment]
This is hard.

**Comment by isaacovercast** [comment]
data.dirs order: fastq, edits, clusts, consens, outfiles

also the order of the summarized stats in data.stats should start with state and then show results for each of steps 1-5

and samples.statsfiles

**Comment by isaacovercast** [comment]
All ObjDict based: data.dirs, data.statsfiles, sample.statsfiles are sorted at access time when print() or str() is called. This is hackish, but it works, and the alternative (implementing an ordered version of ObjDict) gets very cumbersome.

samples.stats is a pandas series, so that was much easier to simply reorder inside load_json()

**Comment by isaacovercast** [comment]
I think this is done.
