### ISSUE TITLE
assembly_method as an assembly.parameter rather than a flag to step3()?

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#12]
I was thinking about making assembly_method a parameter in the assembly paramsdict, rather than a flag to step3(). I like the idea of being able to specify denovo, reference, or hybrid specifically, for instance if you JUST want to keep the reference mapped reads, or if you specify a reference seq, but you wan't to TRY denovo. I think it'd work better as a parameter tho, because then I could reach out and test assembly_method from the handful of different codeblocks that handle refseq mapping, rather than passing the argument around. Thoughts?

**Comment by dereneaton** [comment]
Yeah, that makes sense. Anything that would belong in the old style params file should be in the paramsdict. This is certainly important enough to warrant inclusion. 

On a related note, we probably want to keep the paramsdict fairly short so that it's easily readable. Perhaps we could have the basic paramsdict, and an extended paramsdict to modify flags that will probably not be used very often. Maybe an "extrasdict" attribute to Assembly objects.

**Comment by isaacovercast** [comment]
Lol we should call it "hackersonly_dict"... Agreed paramsdict should be kept lean, but it seems for backward compatibility we'd have to keep all the pyrad v2 params in there. Do you anticipate adding many more flags in the future? Perhaps we should sit on this and see how many new parameters accumulate. If it starts to get hairy i agree an 'extradict' would be a good solution, but for now it seems to add a lot of overhead.

**Comment by isaacovercast** [comment]
Added assembly_method as a param in refseq branch.
