### ISSUE TITLE
Docs: output options not documented

### ISSUE THREAD

**Issue by cdoorenweerd** [dereneaton/ipyrad#221]
The ipyrad readthedocs claims that by default all output formats are generated and under tutorial the ipyrad params file shows at item 27 an *

In version 0.5.1 the params file shows by default on output formats: l, p, s, v
I can find no reference in the docs on what these formats refer to - where can I find all the options?

Thanks in advance

**Comment by isaacovercast** [comment]
The docs were a little out of date so I fixed them to reflect current reality. The current default for output_formats is "p, s, v" (I removed the `l` since it wasn't actually doing anything). I also fixed the docs to reflect the fact that "*" isn't the current default (though it is still available as an option). Explanations for the available output format options are here: http://ipyrad.readthedocs.io/parameters.html#output-formats

Full information about all output formats is here: http://ipyrad.readthedocs.io/output_formats.html#full-output-formats
