### ISSUE TITLE
Refmap - Step 6 speedup

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#254]
Got a good suggestion from a user. If we actually use position information for reference mapped loci during step 6 clustering it would be MUCH faster than using vsearch to do it the hard way. This is actually a good idea and would probably speed up clustering for refmapped by > 10x, maybe more.

**Comment by dereneaton** [comment]
Yes, we talked about this the other day. Seems like it could be done easily by writing the data into SAM/BAM format and pulling out overlapping consens reads with bedtools like we do in step3. It will take some testing though to make sure no funny business pops up, especially for partially overlapping sequences. But I think it will work. High on the TODO list.

**Comment by pimbongaerts** [comment]
That is really great to hear - thanks so much for considering the suggestion. For my most recent dataset (664 samples with ref genome), I had to abandon ipyrad unfortunately because of speed issues (although in part this seemed to do with problems detecting available CPUs on AWS EC2 instance) - but this might hopefully solve that!

**Comment by isaacovercast** [comment]
implemented in v0.9. nice work.
