### ISSUE TITLE
Step 6 - IndexError(too many indices for array)

### ISSUE THREAD

**Issue by cjlewis7** [dereneaton/ipyrad#296]
Hello, 

I am trying to reference assemble 1 sample to a transciptome (to use as a reference for other samples later).  It seems to run fine until the end of Step 6 when I get an error while trying to Index Clusters: "IndexError(too many indices for array)"

Do I need to include more than one sample?

Thank you!

**Comment by isaacovercast** [comment]
What version of ipyrad are you running? Can you re-run step 6 with the `-d`
flag and post the last several lines of the ipyrad_log.txt file? It
_should_ work with 1 sample, but I can't recall ever having tried.

**Comment by cjlewis7** [comment]
I am running version 2.7. 

And I've attached the last part of the log. 

Thanks for your help
[IndexError.txt](https://github.com/dereneaton/ipyrad/files/2041143/IndexError.txt)

**Comment by isaacovercast** [comment]
Hm, you mean 0.7? 2.7 isn't a version of ipyrad. It looks like a more recent version from the output you sent. Can you dropbox me this file: /lus/scratch/clewis7/ip_tenuismidway_2/ip_tenuismidway_2_consens/3273-PM-0001_S1_L001001.consens.gz

**Comment by isaacovercast** [comment]
Nevermind, you were correct when you guessed that you need to assemble more than one sample. If all you're interested in is using the aligned sample as a reference, you can just use the *.consens.gz file inside the _consens/ directory, this is gzipped fasta format.

I'm marking this as 'fixed' since support for assembling 1 sample is an edge case.

**Comment by cjlewis7** [comment]
Thank you!
