### ISSUE TITLE
Preview mode is not working in 0.7.15

### ISSUE THREAD

**Issue by bioballs** [dereneaton/ipyrad#302]
Hello,

I run ipyrad version 0.7.15 and it seems like preview mode is not working.

It will not show the expected

Step2: Filtering reads
Running preview mode: subselecting maximum of 100000 reads per sample

and runs last like no subsampling happened. Tried it from step 1 and step 2.

Greets
Armin

**Comment by isaacovercast** [comment]
Hi Armin,
Yeah, preview mode is kind of a legacy feature that we initially thought was a good idea, but eventually we stopped working on it. I'm kind of _surprised_ that it doesn't work still because what its doing is pretty straightforward, but this should be considered a deprecated feature which will be removed at some point in the future. When I need to run small samples of data I'll normally subsample the raw fastq files by hand: `gunzip -c <sample1.fq.gz> | head -n 100000 > sample1.fq` to grab the first 250k reads.

**Comment by isaacovercast** [comment]
Since preview mode isn't supported and isn't going to be fix i'm going to close this ticket. If you feel like fixing it we do accept PR ;)

**Comment by isaacovercast** [comment]
I looked into this more and in fact the remains of preview mode in the current version are just stubs, so it doesn't even pretend to do anything. I removed the stubs from the current version, to prevent future confusion.
