### ISSUE TITLE
output_format(s)

### ISSUE THREAD

**Issue by bryansmclean** [dereneaton/ipyrad#324]
Im curious if it is possible to output standard alignment files (.phy or .nex) as raw alleles in addition to ambiguity-coded data?

Alternatively, is there an ipyrad parser for *alleles.loci files that already does this?

Best,
bryan

**Comment by isaacovercast** [comment]
Hey Bryan,
There's no parser to do this automatically. I think this would be tricky because phase is only known _within_ each rad locus, so something to paste together all the alleles for each individual would be improperly (and inaccurately) phasing the data. Can you give me a better idea what you're trying to do?

**Comment by bryansmclean** [comment]
Isaac,

I just meant that there are a range of (possible) output files which are parsed from the consensus loci. But the alleles are only available in the *alleles.loci output file and not parsed into any of these formats. Of course, as you note, calling alleles must be done on a per-locus basis. But this has already been done by ipyrad and seems its just a matter of parsing the results?

As a quick fix, I just wrote a bash script to parse the *alleles.loci file. But such an addition might be helpful in the future as raw alleles are useful for some downstream applications.

Bryan

**Comment by isaacovercast** [comment]
Not sure this issue is still relevant, so closing it. If there are output files that can be generated that contain the within locus linkage linkage information without simply concatenating all the loci together in a random fashion, I'm not aware of it. If there's a concrete suggestion for what this format might look like please reopen the issue and describe it so we can implement.
