### ISSUE TITLE
ipyrad Permission denied error 

### ISSUE THREAD

**Issue by caranlove** [dereneaton/ipyrad#339]
Hi all, 
I am running into a new issue while running ipyrad on 3RAD data. I am new to running ipyrad so please bare with me. 

I am running ipyrad remotely and am using ipyrad/0.7.24-foss-2016b-Python-2.7.14. The runs seems to be initiating fine, but runs into an issue with my input files (e.g. reference fasta file and population txt file) with an error of "Permission denied". I am attaching a copy of the error message I am receiving below and wonder if anyone knows how to remedy this issue? 

Thanks all!  

The error I am receiving is:
sapelo2.SC: line 14: ipyrad-Ante: command not found
sapelo2.SC: line 15: ./: Is a directory
sapelo2.SC: line 18: /ipyrad/Ante: Is a directory
sapelo2.SC: line 19: reference: command not found
sapelo2.SC: line 20: /Reference/Ante_final.fasta: Permission denied
sapelo2.SC: line 21: pair3rad: command not found
sapelo2.SC: line 22: GCTAGA,TAATTC: command not found
sapelo2.SC: line 23: 5: command not found
sapelo2.SC: line 24: 33: command not found
sapelo2.SC: line 25: 6: command not found
sapelo2.SC: line 26: 6: command not found
.sapelo2.SC: line 27: 100: command not found
sapelo2.SC: line 29: 1: command not found
sapelo2.SC: line 30: 2: command not found
sapelo2.SC: line 31: 35: command not found
sapelo2.SC: line 32: 2: command not found
sapelo2.SC: line 33: 5,: command not found
sapelo2.SC: line 34: 8,: command not found
sapelo2.SC: line 35: 4: command not found
sapelo2.SC: line 36: 20,: command not found
sapelo2.SC: line 37: 5,: command not found
sapelo2.SC: line 38: 0.5: command not found
sapelo2.SC: line 39: 0,: command not found
sapelo2.SC: line 40: 10,: command not found
sapelo2.SC: line 41: A1123_P6.1.fq.gz: command not found
sapelo2.SC: line 42: /Ante/Ante_ipyrad_populations.txt: Permission denied

**Comment by isaacovercast** [comment]
Hello! Well first this doesn't look like an ipyrad issue. It looks like you're trying to run the params file directly as a script. These are all terminal errors that would arise from doing something like this:

./params-assembly.txt

But the params file is only the parameters file for ipyrad, which is the executable. You need to do something more like this: ipyrad -p params-assembly.txt -s 1234567

The please verify that your job submission script is correctly formatted. Also, in the future it's great to post stuff like the full job submission script, and the params file. Also, since this is not an ipyrad issue, but rather a usage issue i'm going to close this ticket and I'll encourage you to join the [ipyrad gitter channel](https://gitter.im/dereneaton/ipyrad), which is more appropriate for discussion and questions.
