### ISSUE TITLE
Refseq mapping - <pair> handle r1 and r2 of different lengths?

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#34]
Would this ever come up in reality? It might, and if it does then the pipeline will fail hard if you don't test for it..

**Comment by dereneaton** [comment]
It's not only possible, but likely that the reads will be different length, due to the fact that barcodes are trimmed off R1s. Users might often input their own data that has been trimmed or filtered in some other way as well. In step2 we currently enforce that R2 is trimmed down to the len of R1 for pairgbs data, enforcing it for all paired data types would resolve any problems that could arise from this with the minimal cost of removing a little bit of data that could otherwise be salvaged in pairddrad data types (4-10 bp). We could enforce the trimming only if refseq mapping is turned on, but that could create a problem if users don't have refseq turned on at first and then turn it on later in step3.

**Comment by isaacovercast** [comment]
Should have clarified, This is referring to the .gz files containing different # of reads. Refmapping can handle variable read lengths for R1 and R2, no problem, but different R1/R2 file sizes makes it fail hard.

**Comment by dereneaton** [comment]
Oh, yeah, that shouldn't happen. We can add an assertion to ensure it, but unless users edit the files themselves nothing in ipyrad should lead to unequal numbers of reads in R1 and R2 files.

**Comment by isaacovercast** [comment]
Added a try/catch around the call to smalt with some helpful debug message in the event this arises. For future reference, the exit code when r1/r2 files are different lengths is 1.
