### ISSUE TITLE
step3 error

### ISSUE THREAD

**Issue by dxkyq917** [dereneaton/ipyrad#341]
Hi, everyone
when I run step3 for ten days, I get the following error. 
This is my code and logfile.

![image](https://user-images.githubusercontent.com/31763354/56938598-685ee900-6b35-11e9-9b40-21425975163e.png)

![image](https://user-images.githubusercontent.com/31763354/56938610-76146e80-6b35-11e9-850c-c045c59a80e5.png)

![image](https://user-images.githubusercontent.com/31763354/56938643-b07e0b80-6b35-11e9-962c-97e9ac924f61.png)

Looking forward to your help

**Comment by isaacovercast** [comment]
This is almost certainly a resource issue. In this case it looks like you've run out of disk space. Step 3 is probably the most disk intensive step, in terms of volume of temporary files created. It's a little hard to estimate, but I would say you need to have around 10x the size of your raw data in free disk space for step 3. Maybe more, but this is on the right order. Also, 4GB of RAM per core is our _minimum_ recommendation. This isn't causing the problem here, but it may speed up your assembly.
