### ISSUE TITLE
STRUCTURE k=1?

### ISSUE THREAD

**Issue by pabuveery** [dereneaton/ipyrad#400]
Hi! I've been using the STRUCTURE component of iPYRAD analysis through a Jupyter notebook, and I was wondering whether it is possible to run STRUCTURE with k = 1. I've been able to successfully complete analyses at k = 2-5, but when I input the following line:

struct1.run(kpop=1, nreps=10, auto=True)

I get the following error:

Encountered an Error.
Message: list.remove(x): x not in list
Traceback (most recent call last):
  File "/gpfs/ysm/project/prum/mdh57/conda_envs/new_ipyrad/lib/python2.7/site-packages/ipyrad/core/Parallel.py", line 313, in wrap_run
    self.tool._run(ipyclient=self.ipyclient, **self.rkwargs)
  File "/gpfs/ysm/project/prum/mdh57/conda_envs/new_ipyrad/lib/python2.7/site-packages/ipyrad/analysis/structure.py", line 364, in _run
    jobs.remove(i)
ValueError: list.remove(x): x not in list

Thanks for taking a look!

**Comment by isaacovercast** [comment]
Hello @pabuveery. I don't know what's going on because it works for me. Can you show me all the output it produces when you call that function? Are you on the most recent version of ipyrad? What version are you on? Can you show more of your notebook code so I can see context? What happens if you just try to run this:

struct1.run(kpop=2, nreps=10, auto=True)

**Comment by isaacovercast** [comment]
![image](https://user-images.githubusercontent.com/5974975/79641228-75d21080-8196-11ea-9565-de860fa44216.png)

**Comment by pabuveery** [comment]
Thank you so much, I just ran the above code and it worked. Not totally sure what happened but I think I must have been improperly defining the STRUCTURE job. Either way, thank you for your help!
