### ISSUE TITLE
Can't build targets without any engines

### ISSUE THREAD

**Issue by djlduckett** [dereneaton/ipyrad#408]
Hi there. About a year ago, I had installed and run ipyrad on our cluster, and everything worked fine. I am now trying to run it on a different dataset, but I get the error:

 >-------------------------------------------------------------
 > ipyrad [v.0.7.29]
 > Interactive assembly and analysis of RAD-seq data
 >-------------------------------------------------------------
 > New Assembly: microtus_30
 >
 > Encountered an error (see details in ./ipyrad_log.txt)
 > Error summary is below -------------------------------
 >   No ipcluster instance found. This may be a problem with your installation
 >   setup, or it could be that the cluster instance isn't firing up fast enough.
 >   This most often happens on cluster nodes. One solution is to launch
 >   ipcluster by hand and then pass the `--ipcluster` flag to ipyrad. See
 >   the docs for more info: http://ipyrad.rtfd.io/HPC_script.html

-------------------------------------------------------------
I went to the suggested docs page, and changed my script to start ipcluster manually and sleep for 60 seconds before starting the analysis as suggested, but then I get the error:

>-------------------------------------------------------------
>ERROR:ipyrad.core.assembly:Can't build targets without any engines
>
> -------------------------------------------------------------
>  ipyrad [v.0.7.29]
>  Interactive assembly and analysis of RAD-seq data
> -------------------------------------------------------------
>  New Assembly: microtus_30
>
>
>  Step 1: Loading sorted fastq data to Samples
>  30 fastq files loaded to 30 Samples.
>
>  Step 2: Filtering reads 
>
>  Encountered an unexpected error (see ./ipyrad_log.txt)
>  Error message is below -------------------------------
>Can't build targets without any engines

-------------------------------------------------------------
I tried increasing the sleep time to 300, but I get the same error. Do you have any advice on how I could fix this or what I might be doing wrong? My pbs script is below:

>-------------------------------------------------------------
>#!/usr/bin/bash
>#PBS -l walltime=50:00:00
>#PBS -l nodes=1:ppn=30
>#PBS -N microtus_ipyrad_12
>#PBS -j oe
>#PBS -A PAA0202
>
>module load bwa
>
>cd $PBS_O_WORKDIR
>
>export PATH="~/miniconda2:$PATH"
>source ~/.bashrc
>
>ipcluster start --n 30 --daemonize
>sleep 300
>
>ipyrad -p params-microtus_30.txt -s 12 --ipcluster

-------------------------------------------------------------
Thank you,
Drew

**Comment by isaacovercast** [comment]
Hi drew,

This is less of an ipyrad issue and more of a user support issue. For user support issues we recommend jumping on the gitter channel: https://gitter.im/dereneaton/ipyrad

v0.7.29 is quite an old version, and many many bug fixes and improvements have been made since then. It's not even the most current version of the 0.7 version. If possible I recommend updating to the most recent version (on the v0.9 minor version number). At the very least update to v0.7.30 and try it again.

Did you try getting an interactive session on a compute node and running the script line by line by hand? Might get more info that way.

You might find some ideas here:

https://groups.google.com/forum/#!topic/pyrad-users/3PAgzcWVcRw

Since this isn't an ipyrad issue per se i'm closing it, but please jump on the gitter channel if you try what i recommend and still can't get it working.

**Comment by djlduckett** [comment]
Hi Isaac. Sorry for the confusion. I will go to the gitter channel in the future, but it looks like updating the version worked.

Thank you,
Drew
