### ISSUE TITLE
Increase verbosity of Preview mode

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#44]
Try to get preview mode to provide more feedback on settings and on what it's doing. What would be useful to know from each step? Fill this in...
- Step 1
  - ?
- Step 2
- Step 3
- 
- Step 4
- Step 5

Done step1 and step2, both of these are similar in that they are already chunking the data for parallel processing, so i just lop off the first chunk and call that good. Seems to work.

```
              if preview:
                   LOGGER.warn( "Running preview mode. Selecting only one chunk to rawedit." )
                   chunkslist = [ chunkslist[i] for i in [0] ]
```

step3 - Already has a more complicated preview mode, does essentially the same thing, truncates a file so it runs fast.

step4 - Not done yet
step5 - Not done yet
step6 - Not done yet
step7 - Not done yet

**Comment by dereneaton** [comment]
Seems like a good idea for 1&2. Certainly good enough for now. 

Step 4 already has a builtin parameter "subsample" which grabs only the first N clusters to use to estimate H & E. This seems like a useful thing to use most of the time, since you never really need to test over huge numbers of clusters to estimate H&E accurately. For example, preview mode could restrict step4 to using the first 1000 clusters. 

steps 5-7 should run fast given that the number of clusters is pretty small per sample. 

The other thing we might want to do in 'preview mode' is to have more verbose output printed to the screen explaining what is happening in each step... For example, in step 2 it would print out that it has detected that adapters are present, and so maybe the user wants to turn filtering.... That might be a bit of work...

**Comment by isaacovercast** [comment]
Preview mode is dead.
