### ISSUE TITLE
AssertionError: Different number of R1 and R2 files

### ISSUE THREAD

**Issue by laaryjc** [dereneaton/ipyrad#447]
Did a new install of conda and iPyrad, and now I'm getting this error at step 1.  
checked the files and there are no extra fastq.gz files inthe folder, ls | wc -l shows 96 samples, F and R files, totalling 192
Any thoughts?  Thanks!

(base) laary@:~/iPyradWork/070121$ ipyrad -p params_070121_micpet.txt -s 1 -f

 -------------------------------------------------------------
  ipyrad [v.0.9.81]
  Interactive assembly and analysis of RAD-seq data
 -------------------------------------------------------------
  Parallel connection | hillary: 64 cores

  Step 1: Demultiplexing fastq data to Samples
  [############        ]  61% 0:08:09 | chunking large files
  Encountered an Error.
  Message: AssertionError: Different number of R1 and R2 files
  Parallel connection closed.

(base) laary@:~/iPyradWork/data$ ls *R1* | wc -l
96
(base) laary@:~/iPyradWork/data$ ls *R2* | wc -l
96
(base) laary@:~/iPyradWork/data$ ls | wc -l
192

**Comment by isaacovercast** [comment]
Question: Do you have 96 pairs of raw data files that are not already demultiplexed? Or do you have 96 pairs of fastq.gz files with one pair (R1/R2) per sample? I _think_ what you want you want is to use the `sorted_fastq_path` parameter in the params file, instead of the `raw_fastq_path`. If your data have already been demultiplexed to samples this is 100% what you want. With pre-demux'd data you still need to run step1, but all it does is read in the numbers of raw reads per sample. Good luck.

**Comment by laaryjc** [comment]
Absolutely correct and such an overlooked mistake.  I read tha tparameter file so many times and didn't see my error in placing the path to the demultiplexed data in the raw reads parameter.  Thanks for the help!
