### ISSUE TITLE
 Message: No samples ready for step 3. If branching, use the `-f` flag to force re-running step 3.

### ISSUE THREAD

**Issue by zilaijuand** [dereneaton/ipyrad#452]
Hi
   I create a branch with a subset of samples.
  ipyrad -p params-iptest1.txt -b subdata popmap/subpop.txt
  loading Assembly: ipyxm1
  from saved path: ~/xmml/iprad/xmml/programfile1/ipyxm1.json
  creating a new branch called 'subdata' with 84 Samples
  writing new params file to params-subdata.txt
  then I run the step3, the following error occurred（step2 is the same）.

Step 3: Clustering/Mapping reads within samples
  skipping samples already finished step 3:
['BP1.', 'BP10.', 'BP2.', 'BP3.', 'BP4.', 'BP5.', 'BP6.', 'BP7.', 'BP8.', 'BP9.', 'BSH1.', 'BSH10.', 'BSH11.', 'BSH12.', 'BSH2.', 'BSH3.', 'BSH4.', 'BSH5.', 'BSH6.', 'BSH7.', 'BSH8.', 'BSH9.', 'BXC1.', 'BXC2.', 'BXC3.', 'BXC5.', 'BXC6.', 'BXC7.', 'BXC8.', 'JYZ1.', 'JYZ10.', 'JYZ11.', 'JYZ12.', 'JYZ13.', 'JYZ14.', 'JYZ15.', 'JYZ2.', 'JYZ3.', 'JYZ4.', 'JYZ5.', 'JYZ6.', 'JYZ8.', 'JYZ9.', 'LB1.', 'LB10.', 'LB11.', 'LB12.', 'LB13.', 'LB14.', 'LB15.', 'LB2.', 'LB3.', 'LB4.', 'LB5.', 'LB7.', 'LB8.', 'LB9.', 'LSH1.', 'LSH10.', 'LSH11.', 'LSH13.', 'LSH14.', 'LSH15.', 'LSH3.', 'LSH4.', 'LSH7.', 'LSH8.', 'LSH9.', 'MCP1.', 'MCP10.', 'MCP11.', 'MCP12.', 'MCP2.', 'MCP3.', 'MCP4.', 'MCP5.', 'MCP6.', 'MCP7.', 'MCP8.', 'MCP9.', 'QCP1.', 'QCP2.', 'QCP3.', 'QCP4.']

  Encountered an Error.
  Message: No samples ready for step 3. If branching, use the `-f` flag to force re-running step 3.
  Parallel connection closed.
 
After created the subsample，how can I avoid this error？
thanks！！！

**Comment by isaacovercast** [comment]
The error message is telling you all you need to know. You ran the assembly through at least step 3, then created a branch. Now you are trying to run step 3 again, but you do not need to, because all the samples in the branch already have been clustered. Hence, if you want to re-run step 3 (even though this is unnecessary) you must use the `-f` flag as is indicated in the error message. Step 2 also indicates the same message because you do not need to re-run step 2 if you branch after step 2 has already been run. You may proceed to step 4 with the subset of samples.

**Comment by zilaijuand** [comment]
Thanks a lot！
