### ISSUE TITLE
Installing ipyrad

### ISSUE THREAD

**Issue by c-mccarron** [dereneaton/ipyrad#472]
Hello, I have been trying to load ipyrad all day and running into issues. I mostly work with Rstudio so this is somewhat new to me but I am following the basic installation instructions in the anaconda environment terminal and it is not working. I have also tried it in jupyter. In the terminal I get the message that the ipyrad only works with python version 2.7 or less and mine is the latest version. I have created a new environment with pythons of different versions and it still hasn't worked. I have done this with version 2.7 and followed up with a environment using version 3.7. This was done because it was noted on a previous issue that version 3.8 had the same notice appearing for someone. This was the recommendation and it fixed it. In the jupyter notebook, it tells me the syntax is wrong. 
How do I go about installing ipyrad?

**Comment by isaacovercast** [comment]
Hi there,
Well it _should_ work as in the docs, I tested it yesterday and it worked fine. Also, the 3.8 version issue was resolved so 3.8 should work fine as well. Can you show me exactly what you are trying and the exact error messages that are given? Please copy/paste the commands you're running and the terminal output. Are you on linux or max? This _should_ work:
```
conda create -n ipyrad python=3.9
conda activate ipyrad
conda install -c conda-forge -c bioconda ipyrad vsearch=2.19
ipyrad -v
```
The vsearch version pin is because of a very recent conflict with the newest version of vsearch, which we hope to have resolved soon. It should impact the install. What happens when you run these exact commands? Happy to help you get it working.

**Comment by c-mccarron** [comment]
Hey, 
First, thank you for you quick reply. This is definitely a huge help. I have been using the linux ubuntu shell on a windows 10 desktop. As I said, I am usually use to using Rstudio in windows 10 so this is all new to me. I am beginning to think that this is due to some mistake on my end with linux/windows. 
As for the error message that it get from the command I ran prior to asking for advice, I get:

(cpDNA) C:\Users\15109>conda install ipyrad -c conda-forge -c bioconda
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.|
                                                                                                                       -failed

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - ipyrad -> python=2.7

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.


I tried to run the commands that you advised and I got this:

(cpDNA) C:\Users\15109>conda activate ipyrad

(ipyrad) C:\Users\15109>conda install -c conda-forge -c bioconda ipyrad vsearch=2.19
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - vsearch=2.19

Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.anaconda.org/bioconda/win-64
  - https://conda.anaconda.org/bioconda/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.


If it is likely that this is just an error on my end with the windows/linux interface that I apologize. If this is something else, any advice would be appreciated. Thank you!

**Comment by isaacovercast** [comment]
Hello, well it _sounds_ like you are trying to do the install inside a windows command line shell. You can see when it fails to find a package for vsearch=2.19 that it's looking in win-64 related channels, which indicates you installed the windows version of conda as well. In order to run ipyrad on your windows machine you need to use [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/learn/modules/get-started-with-windows-subsystem-for-linux/), which actually requires a little work to install. Then you can install the _linux_ version of conda inside your WSL installation and _then_ you can install ipyrad as I suggested. Like I said, ipyrad on windows inside WSL is _supposed_ to work just like inside regular linux, but getting WSL installed and running is up to you. Good luck!
