### ISSUE TITLE
Recover all sites (invariant sites) in vcf

### ISSUE THREAD

**Issue by biolevol** [dereneaton/ipyrad#479]
Hello, 
Let me first thank you for this great tool. I was wondering if there is any way I could obtain all invariant sites that are actually covered by the ddRAD reads in our final vcf file, something similar to "--include-non-variant-sites/ -all-sites" from the GATK's GenotypeGVCFs argument. 
Thank you very much in advance!

**Comment by isaacovercast** [comment]
Thanks for the positive feedback, glad you like ipyrad! As for your question, in fact we _used_ to write out the full vcf including invariant sites by default. This file got really really huge, typically, so eventually we switched to only writing out variable sites by default, and allowing including all sites as an option (this was pre v0.9). In version 0.9 we redid the output writing code, and never reimplemented the "full vcf" output as an option, because we never used it personally, and we never heard of anybody using it, so we didn't prioritize reimplementing this.

I will leave this issue open, but honestly I don't see this getting done any time soon, unless one or the other of Deren or myself _needs_ it for a project. It would be a medium sized job, and I don't have many spare cycles at the moment.

Out of curiosity, what is the use case you're interested in? If it seems like a general use case that more people would take advantage of then this would bump the priority a bit.

**Comment by biolevol** [comment]
Dear Isaac, 

Could you please share with us the part of the code that would require changing/adjusting for the full vcf option and we could try to reimplement the full vcf, if that's ok with you. 
Thank you very much in advance.

**Comment by biolevol** [comment]
Thank you very much! 
I will keep you posted for any updates.

**Comment by isaacovercast** [comment]
Here is a workaround to get the full vcf file from an ipyrad loci file.

Download this file and rename it to `loci2vcf.py`
[loci2vcf.py.txt](https://github.com/dereneaton/ipyrad/files/12718584/loci2vcf.py.txt)

Run the python script like this:

`python loci2vcf.py wat.loci out.vcf samps.txt False`

* wat.loci should be replaced with the full path to your `.loci` file
* out.vcf is the name of the output vcf file to write, you can call this whatever you want
* The `samps.txt` file needs to be a file containing a list of all sample names in the vcf, one sample name per row.
* The last argument tells whether to write the full vcf (with monomorphic sites). It should be `True` or `False` (defaults to True). True means write all sites, False means only write snps.

I tested this using the most recent .loci file from the simulated data using ipyrad v0.9.93 and python3.10. It should work for you but no promises.

**Comment by isaacovercast** [comment]
closing this issue because it seems resolved
