### ISSUE TITLE
changing VSEARCH default threads

### ISSUE THREAD

**Issue by Phismil** [dereneaton/ipyrad#480]
Good day, Isaac et al.,
I am currently running ipyrad on a big dataset. I noticed that VSEARCH clustering is taking very long. 
I see in the source code that the default number of threads in this step is "2". I tried the "-t"  flag to increase it to 10 or even 20,  but did not notice any changes in the speed, and step 3 still is a major bottleneck in my dataset.
I am wondering if you have any recommendations to speed up this step.
Thank you in advance

**Comment by isaacovercast** [comment]
Hello Phismil, how much RAM are you allocating? And how many cores? We recommend 4GB per core at the minimum, and if you have paired end data or long reads (>150bp) then more will be required. If you don't have enough ram per core then step 3 will crawl no matter what you do (-t won't help).

Since this is more of a question about operation and not an issue with ipyrad I would suggest we move the discussion to the ipyrad gitter channel, how does that sound? I will close this issue once we pick up the discussion on gitter.

https://gitter.im/dereneaton/ipyrad
