### ISSUE TITLE
Problem installing ipyrad on ubuntu

### ISSUE THREAD

**Issue by kbkinsey** [dereneaton/ipyrad#529]
Hi there - 

I installed and used ipyrad before on my lab's ubuntu computer, but I went back to branch at step 7 and apparently ipyrad is no longer installed on the machine. I went to go re-install ipyrad using the resources at the pages below and none of these install methods are working. 

When I run "conda install -c bioconda ipyrad" it gets stuck on solving the environment. It says "failed with initial frozen solve. Retrying with flexible solve"... Then that fails too... I've tried workaround for the past 2 hrs and nothing will do. 

Any help is appreciated. 

Thanks.

**Comment by isaacovercast** [comment]
Hi Kinsey,

Did you try including the conda-forge channel? `conda install -c conda-forge -c bioconda ipyrad`, that's the recommended install command. If you still have problems being stuck solving the environment you can try swapping out the default solver for the libmamba solver. You can see the commands to do this on the ipyrad install docs page: https://ipyrad.readthedocs.io/en/master/3-installation.html#fixing-conda-install-stuck-on-solving-environment

Let me know how it goes.
-isaac

**Comment by khorikhori** [comment]
Hi there-
Error occurred even libmanda is installed in Ubuntu 20. 

(base) ubuntu@ipXXXXX:~$ conda config --set solver libmamba
(base) ubuntu@ipXXXXX:~$ conda install -c conda-forge -c bioconda ipyrad
Channels:
 - conda-forge
 - bioconda
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: / warning  libmamba Added empty dependency for problem type SOLVER_RULE_UPDATE
failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package ipyrad-0.9.10-py_0 requires pysam >=0.15, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
tq ipyrad is installable with the potential options
x  tq ipyrad [0.9.10|0.9.11|...|0.9.93] would require
x  x  mq pysam >=0.15  with the potential options
x  x     tq pysam [0.15.0|0.15.0.1|...|0.20.0] would require
x  x     x  mq python >=2.7,<2.8.0a0 , which can be installed;
x  x     tq pysam [0.15.0|0.15.0.1|0.15.1|0.15.2] would require
x  x     x  mq python >=3.5,<3.6.0a0 , which can be installed;
x  x     tq pysam [0.15.0|0.15.0.1|...|0.21.0] would require
x  x     x  mq python >=3.6,<3.7.0a0 , which can be installed;
x  x     tq pysam [0.15.2|0.15.3|...|0.21.0] would require
x  x     x  mq python >=3.7,<3.8.0a0 , which can be installed;
x  x     tq pysam [0.15.2|0.16.0.1|...|0.22.0] would require
x  x     x  mq python >=3.8,<3.9.0a0 , which can be installed;
x  x     tq pysam [0.16.0.1|0.17.0|...|0.22.0] would require
x  x     x  mq python >=3.9,<3.10.0a0 , which can be installed;
x  x     mq pysam [0.19.1|0.20.0|0.21.0|0.22.0] would require
x  x        mq python >=3.10,<3.11.0a0 , which can be installed;
x  mq ipyrad 0.9.7 would require
x     mq python 2.7.* , which can be installed;
mq pin-1 is not installable because it requires
   mq python 3.11.* , which conflicts with any installable versions previously reported.

Pins seem to be involved in the conflict. Currently pinned specs:
 - python 3.11.* (labeled as 'pin-1')

**Comment by isaacovercast** [comment]
This is a downstream error coming from [bioconda not yet supporting python 3.11 builds](https://github.com/bioconda/bioconda-recipes/issues/37805). You can install ipyrad if you force  python 3.10 in the conda environment: `conda create -n ipyrad python=3.10; conda activate ipyrad`

**Comment by khorikhori** [comment]
Dear Mr. Issac,
Thank you very much for your suggestion.
30 minitues ago, I solved this problem by following methods.

1) Anaconda is not necessary for installation of ipyrad.
2) Just install miniconda 3
   $ wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
   $ bash Miniconda3-latest-Linux-x86_64.sh
   $ source ~/.bashrc
3) conda create -n ipyrad
    conda activate ipyrad
    conda install ipyrad -c conda-forge -c bioconda
 I'd like to test later whether the installed ipyrad run well.

**Comment by isaacovercast** [comment]
Hello, Ok great, glad you got it installed and thank you for sharing the installation instructions. The libmamba problem doesn't occur anymore because in the latest version of miniconda libmamba has been set to the default solver, which is very useful. Good luck!
