### ISSUE TITLE
paired-reads merge pairs

### ISSUE THREAD

**Issue by dereneaton** [dereneaton/ipyrad#7]
Add merge-pairs option back into step 2 (as opposed to asking people to use PEAR). 

Will probably recycle code from pyrad v2 which does this with usearch. Will now use the new vsearch implementation of merge-pairs.

**Comment by dereneaton** [comment]
So an important question is when to merge paired reads... most of this has to do with the case of cleaning up reads that contain adapter sequences. Some thoughts:

- All step3 methods (de novo or reference) need adapter sequences removed (filtering in step2)
- After clustering, de novo works better if reads are merged, but reference probably works better if they are not. 
- So, this means reads should be merged after step2 but before step3 (if at all). 
- I will also allow for users to use externally filtered or merged reads (using link_fastqs). 
- So, I'm adding several args to link_fastqs to indicate if reads are merged and/or filtered already. 



 I need some of your input on this. For de novo clustering I've found that assembling paired reads works much better when

**Comment by isaacovercast** [comment]
True, all step3 methods need adapter sequences removed. Also true that reference mapping works better when they are unmerged. For paired reads I anticipate mapping read pairs, and returning pairs that both don't successfully map in a sensible way (on the same chromosome, within a reasonable distance, etc, etc) to the pyrad pipline, where they can be merged and clustered as per normal. Would it make sense to merge paired reads prior to or during derep_and_sort()? Pairs have to stay together so this seems like the best place to do it. It would also align with the refseq mapping strategy, since i'd like to drop unmapped reads back in the pipeline right ahead of this call.

**Comment by dereneaton** [comment]
OK, I think this is finished. The order of events is:
* [ref] ref mapping
* [denovo] merging reads
* [denovo] combining end-to-end non-merged reads
* [denovo] dereplicating
* [denovo] clustering 
* [ref & denovo] build clusters

**Comment by Christie-ph** [comment]
I have a question fitting somehow into this thread and regarding read handling in ipyrad.
Why does reference mapping work better on unmerged reads?
I am working with MIG‑seq libraries, which are produced with PCR primers and often generate short fragments where overlap‑merging can be beneficial. Therefore, in my case it would make sense to merge paired reads before mapping.
However, I am unsure whether ipyrad actually uses both read pairs in the pairddrad mode.
Is it possible that ipyrad, regardless of the method specified (e.g., pairddrad), is effectively mapping only R1 reads and not R2?
If so, what are my options?
Is there a way to ensure that all reads are merged before mapping, or do I have to perform merging outside of the ipyrad pipeline?
I am currently using ipyrad 0.9.105.

**Comment by isaacovercast** [comment]
Hello,
All paired-end data is always merged regardless of denovo vs reference assembly strategy. Also, ipyrad always uses all R1/R2 sequences for all paired end datatypes. So you are all good on both counts! Good luck!
-isaac

**Comment by Christie-ph** [comment]
Ok, thats great to know. 
But when comparing my read lengths after reference mapping, they are only 150 bp long instead of the expected 300 bp merged reads which generates the de novo pipeline. I have used exactly the same settings using pairddrad method, just replaced denovo with reference and gave the reference path.

**Comment by isaacovercast** [comment]
How are you quantifying locus lengths to compare between the datasets?

**Comment by Christie-ph** [comment]
I have been using samtools on the .bam files

**Comment by isaacovercast** [comment]
The denovo assembly doesn't have bam files, so how are you getting locus lengths for the denovo assembly? How are you getting to this expectation: "expected 300 bp merged reads which generates the de novo pipeline"?

**Comment by Christie-ph** [comment]
for denovo read lengths I have been checking the denovo_clust_database.fa-file in the _across-folder

**Comment by isaacovercast** [comment]
Ok, that is great, that is the right file to look at for denovo locus lengths. In order to understand what's happening I need more information.

When you say this: "I have been using samtools on the .bam files", what command are you running and what are example results that you see?

When you say this: "I have been checking the denovo_clust_database.fa-file in the _across-folder", what command are you running and how are you summarizing the results?

**Comment by Christie-ph** [comment]
Thank you for looking into this with me. I’m still relatively new to this, so the mistake may very well be on my side..
to check the denovo read (locus) lengths, I used the following command:
```
awk '
  /^>/{
    if (NR>1 && seqlen>0) print "denovo", sample, locus, seqlen
    header=substr($0,2)
    split(header, a, "_")
    sample=a[1]
    locus=substr(header, length(sample)+2)
    seqlen=0
  }
  /^[A-Za-z-]+$/{
    gsub(/-/, "")
    seqlen+=length($0)
  }
  END{
    if (seqlen>0) print "denovo", sample, locus, seqlen
  }
' alignment_denovo_clust_database.fa > denovo_seq_length.tsv
```

- for locus lengths in reference based mapping, I summarized the locus lengths in the .bam files in the _refmapping folder using this command
```
echo -e "sample\tmin\tmax" > bam_readlength_minmax.tsv

for bam in *-mapped-sorted.bam; do
    sample=${bam%%-mapped-sorted.bam}
    samtools view "$bam" \
      | awk '($10!="*"){print length($10)}' \
      | sort -n \
      | awk 'NR==1{min=$1} {max=$1} END{print sample"\t"min"\t"max}' sample="$sample" \
      >> bam_readlength_minmax.tsv
done
```

Edit: I finally evaluated the .consens.bam files in the _consens folder this way and found the information about mapped read lengths which I was initially looking for to check which reference genome might be the suitable for my samples.

**Comment by isaacovercast** [comment]
Happy to help. I think it's probably better to compare 'apples to apples', because right now you are looking at two different files from two different parts of the assembly process. Why not compare locus lengths from the *.loci file in the _outfiles directories? These are the actual final results and should be more comparable. Unmerged reads in the reference assembly are going to look like mapped 150bp fragments in that particular bam file, so the result you are finding is not really telling you what you want to know.

**Comment by Christie-ph** [comment]
Of course.. I was trapped in the wrong universe.
Thanks!
