### ISSUE TITLE
MPI - Handle mpi4py prereq?

### ISSUE THREAD

**Issue by isaacovercast** [dereneaton/ipyrad#80]
conda pulls in openmpi, but `pip install mpi4py` requires "A working MPI implementation", which doesn't get pulled in by pip. Figure out a way to maybe guard this in setup.py? Or figure out how to pull in openmpi in setup.py

**Comment by dereneaton** [comment]
\*sigh\*, it would be so easy if we just forced people to use conda. Do you think its easy to pull in an install of openmpi in pip? Especially for people working on an HPC system the conda install is ideal b/c it gives them a local mpi install, instead of having to load a sys module. With the current code I think there are at least 3 things that conda gets which pip doesn't:

1. hdf5 headers
2. mpi implementation
3. numba compiler libraries (although we don't have to use numba, I was hoping to go back and jit compile more functions later. Currently its only used in dstats calcs.
4. and maybe cython compiler libraries too.

**Comment by isaacovercast** [comment]
pip install unsupported.
